# Generated by Django 3.2.10 on 2022-01-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_Russian',
            fields=[
                ('seq', models.IntegerField()),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('date', models.CharField(max_length=200)),
                ('time_length', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('medium', models.CharField(max_length=200)),
                ('text_type', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
