# Generated by Django 3.2.10 on 2022-01-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('Text_POS', models.TextField()),
                ('Only_POS', models.TextField()),
                ('Text_Lemma', models.TextField()),
            ],
        ),
    ]
